# Generated by Django 2.0.5 on 2018-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180813_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacaocredito',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='creditobancario',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='documentolote',
            name='tipo_documento',
            field=models.IntegerField(blank=True, choices=[(10, 'Contrato de Assentamento'), (20, 'Contrato de Concessão de Uso - CCU'), (30, 'Título Definitivo - não registrado'), (40, 'Título Definitivo - registrado cartório'), (50, 'Matrícula da Propriedade'), (999, 'Não possui')], null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='opcao_ensino_utilizada',
            field=models.IntegerField(blank=True, choices=[(10, 'Frequenta escola em outro assentamento'), (20, 'Frequenta escola na cidade mais próxima'), (10, 'Deixa de frequentar a escola'), (10, 'Outros'), (199, 'Não se aplica')], null=True, verbose_name='Opção de ensino utilizada'),
        ),
        migrations.AlterField(
            model_name='praticaconservacionista',
            name='tipo_pratica',
            field=models.IntegerField(blank=True, choices=[(10, 'Adubação verde'), (20, 'Curvas em nível'), (30, 'Rotação/consórcio de culturas'), (40, 'Adubação orgânica'), (50, 'Cordões de vegetação em nível'), (60, 'Controle alternativo de pragas e doenças'), (70, 'Agrofloresta'), (80, 'Plantios de árvores para proteção de mananciais / áreas degradadas'), (90, 'Não se aplica')], null=True, verbose_name='Prática Conservacionista'),
        ),
        migrations.AlterField(
            model_name='problemaambiental',
            name='tipo_problema',
            field=models.IntegerField(blank=True, choices=[(10, 'Erosão (laminar, sulco, voçoroca)'), (20, 'Compactação do solo'), (30, 'Contaminação por uso de  agrotóxicos/destinação inadequada de embalagens'), (40, 'Exposição de lixo de forma inadequada (a céu aberto)'), (50, 'Queima de lixo'), (60, 'Destinação inadequada de pilhas/baterias/lixo eletrônico'), (70, 'Poluição/contaminação nascente e/ou rios/córregos'), (80, 'Assoreamento de rio/córrego'), (90, 'Queimadas'), (100, 'Desmatamento'), (110, 'Outros'), (999, 'Não se aplica')], null=True, verbose_name='Tipo de problema'),
        ),
    ]
