# Generated by Django 2.0.5 on 2018-08-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membro_codigo_familia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['codigo_familia', 'pk']},
        ),
    ]
